pipeline {
    agent any
    def  mvn_version = 'maventest'
    withEnv(  ["PATH+MAVEN=${tool mvn_version}/bin"] )  {
      //sh "mvn clean package"
    }
    tools { 
        maven 'maventest' 
    }
    stages {
        stage('Build') {
            steps{
                sh "mvn clean package"
            
            }
            
         }
        
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
